#include helpers.inc;
#include classMatches.inc;
// **************************************************************************************							 
function alert(fname, matchedText)
{	
	var ri = new TReportItem();
	ri.LoadFromFile(fname);
	ri.affects = "Web Server";
	ri.alertPath = "Scripts/" + fname; 	
		
	ri.setHttpInfo(lastJob);
	
	if (matchedText) 
		ri.Details =  ri.Details + "[break]Pattern found: [pre][blue]" + matchedText + "[/blue][/pre]";	
	
	addHTTPJobToCrawler(lastJob, 1, 1);
	AddReportItem(ri);	
}							 
// **************************************************************************************							 
function request(uri)
{
	lastJob = new THTTPJob();
		
	lastJob.url = scanURL;
	lastJob.verb = 'GET';
	lastJob.URI = uri;
	lastJob.addCookies = false;
	lastJob.request.addHeader('User-Agent', '<script>alert(12345)</script>', true);
	lastJob.execute();	
	if (!lastJob.wasError && lastJob.response.msg2 == 404)
	{
		return true;
	}	
	
	return false;
}
// **************************************************************************************
function Test1()
{
	var urls = [
					"/inexistent_file_name.inexistent0123450987.cfm"
				];
	
	matches.plainArray = [
						'<script>alert(12345)</script>'
					  ];
	
	matches.regexArray = [
					  ];	
	
	for (var i=0;i<urls.length;i++)
	{ 	
		if (request(urls[i]))
		{
			var matchedText = matches.searchOnText(lastJob.response.body);	
			if (matchedText)
				alert("ColdFusion_User-Agent_Cross-Site_Scripting.xml", matchedText); 	
		}
	}
}
// **************************************************************************************	
function startTesting()
{
	Test1();
}
/***********************************************************************************/
/* main entry point */
var matches = new classMatches();
var lastJob = null;
startTesting();
