// small list of usernames and passwords
var Usernames = Array(
  "sa",
  "root",
  "tmp",
  "temp",
  "test",
  "tst",
  "admin",
  "newuser",
  "nobody"
);
var Passwords = Array(		
  "sa",  
  "trustno1",
  "password",
  "12345",
  "qwerty",  
  "none",
  "root",
  "toor",
  "temp",
  "test",
  "tst",  
  "admin",
  "nobody",
  "changeme",
  "changeme123",
  "4dm1n",
  "wampp",
  "xampp"      
);