#include string_helpers.inc;
#include reporting_helpers.inc;
// test for Nuclear rat
// http://h4ck-y0u.org/viewtopic.php?t=33251
if (IsPortOpen(190)){
	socket = new TSocket("TCP");
	socket.Host = ScanHost;
	socket.Port	= 190;
	socket.Timeout = 5;
	socket.Connect();
	if (socket.IsConnected) {
		//trace("connected");
		req = strFromRawData(0xFF, 0x00, 0x00, 0x00,  0x00, 0x00, 0x00, 0x00,  0x00, 0x00, 0x00, 0x00,  0x00);
		socket.send(req);	
		resp = socket.ReceiveBytes(13);
		//trace(resp);
		if (resp == strFromRawData(0xFF, 0x0F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00))
		{
			trace("trojan Nuclear detected! - alert here");
			ReportItem("Trojan.xml", "The Nuclear trojan horse is running on TCP port 190.");
		}
		socket.Close();
	}
}
