#include constants.inc;
#include classFileTampering.inc;
var targetUrl = new TURL(scanURL.url);
var scheme = getCurrentScheme();
targetUrl.path = scheme.path;
targetUrl.getVar = "";
// main entry point 
for (var i=0;i<scheme.inputCount; i++)
{
	var tester = new classFileTampering(targetUrl, null, scheme, i);
	tester.startTesting();
	ScriptProgress(ComputeProgress(i, scheme.inputCount));
	tester = null;
}
