#include constants.inc;
#include classSQLInjection.inc;
var targetUrl = new TURL(scanURL.url);
var scheme = getCurrentScheme();
targetUrl.path = scheme.path;
targetUrl.getVar = "";
var errorMessages = new classSQLErrorMessages();
// main entry point 
for (var i=0;i<scheme.inputCount; i++)
{
	var tester = new classSQLInjection(targetUrl, errorMessages, scheme, i);
	tester.startTesting();
	ScriptProgress(ComputeProgress(i, scheme.inputCount));
	tester = null;
}
