#include constants.inc;
#include classUnsafePregReplace.inc;
var targetUrl = new TURL(scanURL.url);
var scheme = getCurrentScheme();
targetUrl.path = scheme.path;
targetUrl.getVar = "";
var injectionPatterns = new classInjectionPatterns();
// main entry point 
for (var i=0;i<scheme.inputCount; i++)
{
	var tester = new classUnsafePregReplace(targetUrl, injectionPatterns, scheme, i);
	tester.startTesting();
	ScriptProgress(ComputeProgress(i, scheme.inputCount));
	tester = null;
}
